#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push "nasyalnik/cats-api:travis-$TRAVIS_BUILD_NUMBER"
ssh -i ./deploy_key "$PRODUCTION_USER@$PRODUCTION_SERVER" << EOF
    (docker rm -f cats-api) || true
    docker run -d \
        --name cats-api \
        --network meowle \
        --restart always \
        -e NODE_ENV=production \
        --env-file /data/pg-cats-api.env \
        -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER \
        -v $PWD/public/photos:/app/public/photos \
        -p 3001:3001 \
        "nasyalnik/cats-api:travis-$TRAVIS_BUILD_NUMBER"
EOF
